### 1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

mat1 = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])

mat2 = np.array([[10,11,12],
               [13,14,15],
               [16,17,18]])

add_mat = np.add(mat1, mat2)

print("The sum of two matrix \n\n{}  and \n\n{}  is \n\n{}".format(mat1, mat2, add_mat))

The sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[10 11 12]
 [13 14 15]
 [16 17 18]]  is 

[[11 13 15]
 [17 19 21]
 [23 25 27]]


### 2.	Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])

mat2 = np.array([[10,11,12],
               [13,14,15],
               [16,17,18]])

add_mat = np.multiply(mat1, mat2)

print("The sum of two matrix \n\n{}  and \n\n{}  is \n\n{}".format(mat1, mat2, add_mat))

The sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]]  and 

[[10 11 12]
 [13 14 15]
 [16 17 18]]  is 

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


### 3.	Write a Python Program to Transpose a Matrix?

In [5]:
import numpy as np

mat1 = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
mat1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [6]:
st_ring = input("Enter some words: ")
words = st_ring.split()
words.sort()
for word in words:
    print(word)

Enter some words: hello buffalo chalo
buffalo
chalo
hello


### 5.	Write a Python Program to Remove Punctuation From a String?

In [8]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

inp_ut = input("Enter a string with punctuation: ")

remove_punc = ""

for i in inp_ut:
    if i not in punctuations:
        remove_punc = remove_punc + i
print(remove_punc)

Enter a string with punctuation: i am a messy *^&))!@#~!!!!~~~~~, string
i am a messy  string
